feat(test): :test_tube: Added testing with jest
Added testing for all tsx and ts files in the project except for select few metadata and site crawling files

ReferenceError: require is not defined (blog/page.tsx)